### ISSUE TITLE
Spam check JavaScript not loading

### ISSUE THREAD

**Issue by garretlaxton** [Strategy11/formidable-forms#414]
While doing some QA on the spam check branch (#402) I encountered an error not letting forms submit. Based on the error JavaScript isn't loading when submitting a form.

---

### Environment:
I setup a clean installation of WordPress for this QA.
**WordPress Version:** 5.7.1
**PHP Version:** 7.4.9
**Browser:** Firefox
**Plugins Installed:** Formidable Forms (JS Spam branch #402)
**Active Theme:** Twenty Twenty-One - v1.3

### Error:
![Screenshot_2021-05-12 formidable QA – Just another WordPress site](https://user-images.githubusercontent.com/16290508/118022533-73ef6800-b32a-11eb-8318-18a53874e6fb.png)

### How to Reproduce:
For this I will be using the default _Contact Us_ form.

When submitting a form via the contact form the error will occur not allowing the form to submit. The error doesn't occur when going back to the latest release (4.10.02).

---

If there's anymore information I can provide let me know!

**Comment by Crabcyborg** [comment]
Hi @garretlaxton! Thank you for looking into this.

A couple of things here.

1. As https://github.com/Strategy11/formidable-forms/pull/402 is still an open pull request, you can just make a comment. We've been adding individual issues for the new views editor, but for smaller updates comments work just fine.
2. We log all of our free issues along with our pro issues [here](https://github.com/Strategy11/formidable-pro/issues).
3. I think your issue here, which is the same as the one reported [here](https://github.com/Strategy11/formidable-forms/pull/402#issuecomment-839263352) is that formidable does not use the unminified JavaScript code by default. You need the JavaScript updates in this update in order to get past that JavaScript error. This can be achieved by adding `define( 'SCRIPT_DEBUG', true );` to your website (I put mine in wp-config.php but I feel like this could probably even be added as a code snippet).

I'm going to close this (for the above reasons).

**Comment by garretlaxton** [comment]
Thanks @Crabcyborg for the clarification on where to properly submit reports. However, I did/do have `define( 'SCRIPT_DEBUG', true );` added to my _wp-config.php_ file at the very bottom while receiving this error.

**Comment by stephywells** [comment]
@Crabcyborg Isaac (my son) also tested this and ran into the same error. Can we update the minified JS in the PR? I know this can end up with merge conflicts, but I think that would be better to get an accurate test.

When Isaac tested it, he went to the form preview page and submitted there. Clearing the browser cache didn't help, although he was using the minified js.

**Comment by Crabcyborg** [comment]
> @Crabcyborg Isaac (my son) also tested this and ran into the same error. Can we update the minified JS in the PR? I know this can end up with merge conflicts, but I think that would be better to get an accurate test.
> 
> When Isaac tested it, he went to the form preview page and submitted there. Clearing the browser cache didn't help, although he was using the minified js.

@stephywells I've just pushed a minified version of the JavaScript to the branch. I've also bumped the version to `4.11` on this branch to try kickstarting the `frm.min.js` since I don't think just updating the minified file covers this.

**Comment by stephywells** [comment]
Awesome! Thank you! That should make testing easier.
