### ISSUE TITLE
Date field marks any entry as not valid

### ISSUE THREAD

**Issue by dergoldbroiler** [Strategy11/formidable-forms#466]
maybe after the update there are no valid date entries possible. This issue is very frustrating on a live environment with the form as most important part..

**Comment by dergoldbroiler** [comment]
Just try: https://dev.sommerimquartier.de/test/

**Comment by Crabcyborg** [comment]
I'm going to close this as there isn't enough information here. And since date fields are a Pro feature, this issue doesn't apply to Lite, this isn't the right place.

The link is now broken as this issue is fairly old.

@dergoldbroiler I hope this is fixed now.

If it isn't, I encourage you to reach out to our support at https://formidableforms.com/new-topic/. If you can provide more information, we can help you figure this out there.

Thanks for your help making Formidable better!
